services:
  - type: web
    name: astrology-api
    runtime: python
    repo: https://github.com/your-username/your-repo
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
